### ISSUE TITLE
Error window at start

### ISSUE THREAD

**Issue by Lucreitus** [champloohq/tusk#19]
I've checked the contributor covenant code of conduct page, it says sexualized language is not accepted but TUSK is amazingly SEXY!! What can I say! :)

about the issues...

## Description

1. First of all  "https://gitter.im/tusk/Lobby"   is giving 404 error, just take a look please

2. I have downloaded and installed "tusk-Setup-0.4.0.exe"
at first open there were no errors, just I couldn't change skin to the vibrant ones.. others work great. But I want the vibrant ones. 
After I close and opened it 2nd time I got this error and everytime it starts with this error. I close it and continuie to use.
And have to press f5 to sync, I don't know how did you set for syncing

## Error message

https://www.evernote.com/shard/s4/sh/555e1079-333c-4014-ad5c-63537b2a330e/0432072c649a5a7d35b49dfa9ef021d4

### Enviro

Win 10 Pro, Visual Basic Community with a few C++ sdk, Atom texteditor (not electron devtools) dockers and bla bla
OS Type:        Windows_NT
OS Platform:    win32
OS Release:     6.3.9600

**Comment by klauscfhq** [comment]
> First of all "https://gitter.im/tusk/Lobby" is giving 404 error, just take a look please

Thank you for taking the time to report it.

> After I close and opened it 2nd time I got this error and everytime it starts with this error. I close it and continuie to use.

The issue was fixed on [`705ed22`](https://github.com/champloohq/tusk/commit/705ed22bf747600ce7ebab5ac5f871024451c076). New release will be out very soon.

> Couldn't change skin to the vibrant ones

Due to `Electron`'s limitations, both vibrant themes, at this moment, are **only** available on `Macos`.

> And have to press f5 to sync, I don't know how did you set for syncing

After editing a note you can sync your changes to the Evernote servers by pressing <kbd>Ctrl</kbd> <kbd>S</kbd>

Happy you enjoy the app : )
